version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      custom-network:
        ipv4_address: 172.30.0.2

volumes:
  redis-data:

networks:
  custom-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16